---
all:
  hosts:
    mirsg_dev_omero:
      ansible_host: omero-server-web

    mirsg_dev_db:
      ansible_host: omero-db

  children:
    mirsg_dev:
      hosts:
        mirsg_dev_omero:
        mirsg_dev_db:

    # Group of all OMERO server + web components in this hosts file
    omero:
      hosts:
        mirsg_dev_omero:

    # Group of all OMERO db components in this hosts file
    db:
      hosts:
        mirsg_dev_db:
